module.exports = {
    ORDER_PLACED:'ORDER_PLACED',
    DELIVERED:'DELIVERED',
    CANCELLED:'CANCELLED',
    RTO:'RTO',
    RETURN_RECEIVED_AT_HUB:'RETURN_RECEIVED_AT_HUB',
    READY_TO_SHIP:'READY_TO_SHIP',
    PICKUP_IN_TRANSIT:'PICKUP_IN_TRANSIT',
    PICKUP_SCHEDULED:'PICKUP_SCHEDULED',
    SHIPPED:'SHIPPED',
    SELLER_CONFIRMATION:'SELLER_CONFIRMATION',
    DELIVERED_TO_SELLER:'DELIVERED_TO_SELLER',
    START_SANITIZATION:'START_SANITIZATION',
    RETURN_PICKUP_SCHEDULED:'RETURN_PICKUP_SCHEDULED',
    PICKUP_AT_HUB:'PICKUP_AT_HUB',
    RETURN_PICKED_UP:'RETURN_PICKED_UP',
}

